### ISSUE TITLE
Ever since upgrading to 1.1, I'm getting undefined method `answer' for #<PowerDNS::Pipe:0x00005646732e8910> 

### ISSUE THREAD

**Issue by rgaufman** [johnl/powerdns_pipe#11]
The full exception is:

```
/etc/powerdns/dns_pipe.rb:96:in `answer'
/etc/powerdns/dns_pipe.rb:303:in `soa_record'
/etc/powerdns/dns_pipe.rb:78:in `process'
/etc/powerdns/dns_pipe.rb:348:in `block in <main>'
/var/lib/gems/2.5.0/gems/powerdns_pipe-1.1/lib/powerdns_pipe.rb:101:in `instance_eval'
/var/lib/gems/2.5.0/gems/powerdns_pipe-1.1/lib/powerdns_pipe.rb:101:in `process_query'
/var/lib/gems/2.5.0/gems/powerdns_pipe-1.1/lib/powerdns_pipe.rb:87:in `process_line'
/var/lib/gems/2.5.0/gems/powerdns_pipe-1.1/lib/powerdns_pipe.rb:69:in `run!'
/etc/powerdns/dns_pipe.rb:346:in `<main>'
```

Did the API change?

**Comment by johnl** [comment]
sorry for the uselessly long time to reply here. It looks like an answer method was available via the PowerDNS::Pipe object at one point but was never intended to be used from there (none of the docs mention it, though it was in one test). It got removed during a refactor: https://github.com/johnl/powerdns_pipe/commit/e20edec7139894fa12f45113176c8625be5bca6e
